import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'pt-BR' | 'en-US' | 'es-ES';

interface LanguageContextProps {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  'pt-BR': {
    // Navegação
    'dashboard': 'Painel',
    'requisitions': 'Requisições',
    'new-requisition': 'Nova Requisição',
    'reports': 'Relatórios',
    'settings': 'Configurações',

    // Ações
    'save': 'Salvar',
    'cancel': 'Cancelar',
    'edit': 'Editar',
    'delete': 'Excluir',
    'view': 'Visualizar',
    'print': 'Imprimir',
    'export': 'Exportar',
    'import': 'Importar',
    'search': 'Buscar',
    'filter': 'Filtrar',
    'clear': 'Limpar',
    'submit': 'Enviar',
    'close': 'Fechar',
    'open': 'Abrir',
    'add': 'Adicionar',
    'remove': 'Remover',
    'update': 'Atualizar',
    'create': 'Criar',
    'confirm': 'Confirmar',
    'approve': 'Aprovar',
    'reject': 'Rejeitar',

    // Estados
    'loading': 'Carregando...',
    'success': 'Sucesso',
    'error': 'Erro',
    'warning': 'Aviso',
    'info': 'Informação',
    'pending': 'Pendente',
    'approved': 'Aprovado',
    'rejected': 'Rejeitado',
    'fulfilled': 'Realizado',
    'cancelled': 'Cancelado',

    // Sistema
    'system-name': 'Controle de Abastecimento',
    'fuel-control-system': 'Sistema de Controle de Combustível',
    'profile': 'Perfil',
    'security': 'Segurança',
    'notifications': 'Notificações',
    'system': 'Sistema',
    'theme': 'Tema',
    'language': 'Idioma',
    'dark': 'Escuro',
    'light': 'Claro',
    'system-theme': 'Sistema',
    'enabled': 'Ativado',
    'disabled': 'Desativado',

    // Dashboard
    'total-requests': 'Total de Requisições',
    'pending-requests': 'Requisições Pendentes',
    'approved-requests': 'Requisições Aprovadas',
    'fuel-consumption': 'Consumo de Combustível',
    'monthly-consumption': 'Consumo Mensal',
    'weekly-consumption': 'Consumo Semanal',
    'consumption-by-department': 'Consumo por Departamento',
    'consumption-by-fuel-type': 'Consumo por Tipo de Combustível',
    'recent-activity': 'Atividade Recente',
    'quick-stats': 'Estatísticas Rápidas',

    // Requisições
    'requisition': 'Requisição',
    'requisition-number': 'Número da Requisição',
    'requisition-date': 'Data da Requisição',
    'requester': 'Solicitante',
    'department': 'Departamento',
    'fuel-type': 'Tipo de Combustível',
    'quantity': 'Quantidade',
    'priority': 'Prioridade',
    'status': 'Status',
    'justification': 'Justificativa',
    'approver': 'Aprovador',
    'approval-date': 'Data de Aprovação',
    'needed-date': 'Data Necessária',
    'request-date': 'Data de Solicitação',
    'details': 'Detalhes',
    'actions': 'Ações',

    // Tipos de combustível
    'gasoline': 'Gasolina',
    'ethanol': 'Etanol',
    'diesel': 'Diesel',
    'diesel-s10': 'Diesel S10',

    // Departamentos
    'logistics': 'Logística',
    'maintenance': 'Manutenção',
    'administration': 'Administração',
    'operations': 'Operações',
    'transport': 'Transporte',

    // Prioridades
    'low': 'Baixa',
    'medium': 'Média',
    'high': 'Alta',
    'urgent': 'Urgente',

    // Formulários
    'required-field': 'Campo obrigatório',
    'select-option': 'Selecione uma opção',
    'enter-value': 'Digite um valor',
    'invalid-email': 'E-mail inválido',
    'password-too-short': 'Senha muito curta',
    'passwords-dont-match': 'Senhas não coincidem',
    'form-errors': 'Corrija os erros no formulário',
    'form-saved': 'Formulário salvo com sucesso',

    // Relatórios
    'generate-report': 'Gerar Relatório',
    'report-period': 'Período do Relatório',
    'start-date': 'Data Inicial',
    'end-date': 'Data Final',
    'report-type': 'Tipo de Relatório',
    'consumption-report': 'Relatório de Consumo',
    'requisitions-report': 'Relatório de Requisições',
    'department-report': 'Relatório por Departamento',
    'fuel-type-report': 'Relatório por Tipo de Combustível',
    'monthly-reports': 'Relatórios Mensais',
    'weekly-reports': 'Relatórios Semanais',
    'annual-reports': 'Relatórios Anuais',

    // Configurações
    'general-settings': 'Configurações Gerais',
    'user-preferences': 'Preferências do Usuário',
    'system-settings': 'Configurações do Sistema',
    'notification-settings': 'Configurações de Notificação',
    'change-password': 'Alterar Senha',
    'current-password': 'Senha Atual',
    'new-password': 'Nova Senha',
    'confirm-password': 'Confirmar Senha',
    'new-requisitions': 'Novas Requisições',
    'pending-approvals': 'Aprovações Pendentes',
    'requisition-status': 'Status de Requisições',
    'personal-info': 'Informações Pessoais',
    'contact-info': 'Informações de Contato',

    // Usuário
    'username': 'Nome de usuário',
    'full-name': 'Nome completo',
    'email': 'E-mail',
    'phone': 'Telefone',
    'position': 'Cargo',
    'role': 'Função',
    'last-login': 'Último acesso',
    'account-created': 'Conta criada',

    // Mensagens
    'no-data': 'Nenhum dado encontrado',
    'no-results': 'Nenhum resultado encontrado',
    'loading-data': 'Carregando dados...',
    'save-success': 'Salvo com sucesso',
    'delete-success': 'Excluído com sucesso',
    'update-success': 'Atualizado com sucesso',
    'operation-failed': 'Operação falhou',
    'confirm-delete': 'Tem certeza que deseja excluir?',
    'confirm-action': 'Tem certeza que deseja continuar?',
    'unsaved-changes': 'Há alterações não salvas',

    // Paginação
    'page': 'Página',
    'of': 'de',
    'items-per-page': 'Itens por página',
    'total-items': 'Total de itens',
    'previous': 'Anterior',
    'next': 'Próximo',
    'first': 'Primeiro',
    'last': 'Último',

    // Data e hora
    'today': 'Hoje',
    'yesterday': 'Ontem',
    'this-week': 'Esta semana',
    'last-week': 'Semana passada',
    'this-month': 'Este mês',
    'last-month': 'Mês passado',
    'this-year': 'Este ano',
    'date-format': 'DD/MM/AAAA',
    'time-format': 'HH:mm',

    // Impressão
    'print-document': 'Imprimir Documento',
    'print-preview': 'Visualizar Impressão',
    'print-options': 'Opções de Impressão',

    // Sobre
    'version': 'Versão',
    'last-update': 'Última Atualização',
    'developed-by': 'Desenvolvido por',
    'about-system': 'Sobre o Sistema',
    'system-info': 'Informações do Sistema',

    // Traduções adicionais
    'filters': 'Filtros',
    'search-requisitions': 'Buscar requisições...',
    'filter-by-status': 'Filtrar por status',
    'filter-by-department': 'Filtrar por departamento',
    'all-statuses': 'Todos os status',
    'all-departments': 'Todos os departamentos',
    'clear-filters': 'Limpar Filtros',
    'no-results-with-filters': 'Nenhuma requisição encontrada com os filtros aplicados',
    'manage-all-fuel-requisitions': 'Gerenciar todas as requisições de combustível',
    'consumed-liters': 'Litros Consumidos',
    'quick-actions': 'Ações Rápidas',
    'approve-pending': 'Aprovar Pendentes',
    'recent-requisitions': 'Requisições Recentes',
    'view-all': 'Ver todas',
    'fuel-requisitions-overview': 'Visão geral das requisições de combustível',
    'loading-dashboard': 'Carregando dashboard...',
    'loading-reports': 'Carregando relatórios...',
    'create-new-fuel-requisition': 'Criar uma nova requisição de combustível',
    'requisition-form': 'Formulário de Requisição',
    'fill-required-data': 'Preencha os dados necessários para criar uma nova requisição de combustível',
    'fuel-consumption-analysis': 'Análise e estatísticas de consumo de combustível',
    'date': 'Data',
    'enter-full-name': 'Seu nome completo',
    'enter-email': 'seu@email.com',
    'select-department': 'Selecione um departamento',
    'enter-phone': '(11) 99999-9999',
    'enter-position': 'Seu cargo na empresa',
    'save-changes': 'Salvar Alterações',
    'account-info': 'Informações da Conta',
    'account-details': 'Detalhes sobre sua conta no sistema',
    'last-updated': 'Última Atualização',
    'manage-profile-preferences': 'Gerencie seu perfil e preferências do sistema',

    // Modal de detalhes
    'requisition-details': 'Detalhes da Requisição',
    'request-date-label': 'Data de Solicitação',
    'needed-date-label': 'Data Necessária',
    'priority-label': 'Prioridade',
    'approver-label': 'Aprovador',
    'quantity-label': 'Quantidade',
    'justification-label': 'Justificativa',
    'liters': 'Litros',

    // Status badges
    'pendente': 'Pendente',
    'aprovada': 'Aprovada',
    'cumprida': 'Cumprida',

    // Formulário
    'requester-label': 'Solicitante',
    'requester-placeholder': 'Nome do solicitante',
    'department-label': 'Departamento',
    'select-department-placeholder': 'Selecione um departamento',
    'fuel-type-label': 'Tipo de Combustível',
    'select-fuel-type': 'Selecione o combustível',
    'quantity-liters': 'Quantidade (Litros)',
    'quantity-placeholder': 'Ex: 500',
    'justification-label-form': 'Justificativa',
    'justification-placeholder': 'Descreva a necessidade do combustível...',
    'needed-date-form': 'Data Necessária',
    'priority-form': 'Prioridade',
    'medium-priority': 'Média',
    'create-requisition': 'Criar Requisição',

    // Relatórios
    'total-requisitions': 'Total de Requisições',
    'approval-rate': 'Taxa de Aprovação',
    'total-consumed': 'Total Consumido',
    'pending-label': 'Pendentes',
    'export-reports': 'Exportar Relatórios',
    'export-complete-report': 'Exportar Relatório Completo',
    'monthly-analysis': 'Análise Mensal',
    'monthly-trend': 'Tendência Mensal',
    'pt-consumption-by-department': 'Consumo por Departamento',
    'distribution-by-fuel-type': 'Distribuição por Tipo de Combustível',
    'department-details': 'Detalhes por Departamento',
    'fuel-type-details': 'Detalhes por Tipo de Combustível',
    'requisitions-count': 'Requisições',
    'liters-count': 'Litros',
    'fuel-label': 'Combustível',

    // Configurações - Segurança
    'change-password-title': 'Alterar Senha',
    'keep-account-secure': 'Mantenha sua conta segura com uma senha forte',
    'current-password-label': 'Senha Atual',
    'current-password-placeholder': 'Digite sua senha atual',
    'new-password-label': 'Nova Senha',
    'new-password-placeholder': 'Digite sua nova senha',
    'confirm-new-password': 'Confirmar Nova Senha',
    'confirm-password-placeholder': 'Confirme sua nova senha',
    'change-password-button': 'Alterar Senha',
    'security-tips': 'Dicas de Segurança',
    'keep-account-always-secure': 'Mantenha sua conta sempre segura',

    // Configurações - Notificações
    'notification-settings-title': 'Configurações de Notificação',
    'configure-notifications': 'Configure como e quando você deseja receber notificações',
    'new-requisitions-notif': 'Novas Requisições',
    'new-requisitions-desc': 'Receba notificações quando uma nova requisição for criada',
    'pending-approvals-notif': 'Aprovações Pendentes',
    'pending-approvals-desc': 'Notificações sobre requisições aguardando aprovação',
    'requisition-status-notif': 'Status de Requisições',
    'requisition-status-desc': 'Atualizações sobre o status das suas requisições',
    'monthly-reports-notif': 'Relatórios Mensais',
    'monthly-reports-desc': 'Resumo mensal do consumo de combustível',

    // Mensagens de notificação/toast
    'requisition-created-success': 'Requisição criada com sucesso!',
    'requisition-updated-success': 'Requisição atualizada com sucesso!',
    'status-updated-success': 'Status da requisição atualizado com sucesso!',
    'profile-updated-success': 'Perfil atualizado com sucesso!',

    // Fornecedores
    'suppliers': 'Fornecedores',
    'supplier': 'Fornecedor',
    'supplier-management': 'Gerenciar Fornecedores',
    'suppliers-list': 'Lista de Fornecedores',
    'new-supplier': 'Novo Fornecedor',
    'edit-supplier': 'Editar Fornecedor',
    'delete-supplier': 'Excluir Fornecedor',
    'supplier-name': 'Nome Empresarial',
    'supplier-fantasia': 'Nome Fantasia',
    'supplier-cnpj': 'CNPJ',
    'supplier-responsible': 'Responsável',
    'supplier-email': 'Email',
    'supplier-phone': 'Telefone',
    'supplier-address': 'Endereço',
    'search-suppliers': 'Buscar fornecedores...',
    'no-suppliers': 'Nenhum fornecedor encontrado',
    'supplier-created': 'Fornecedor criado com sucesso!',
    'supplier-updated': 'Fornecedor atualizado com sucesso!',
    'supplier-deleted': 'Fornecedor excluído com sucesso!',
    'error-creating-supplier': 'Erro ao criar fornecedor',
    'error-updating-supplier': 'Erro ao atualizar fornecedor',
    'error-deleting-supplier': 'Erro ao excluir fornecedor',
    'password-changed-success': 'Senha alterada com sucesso!',
    'report-generated-success': 'Relatório gerado com sucesso!',
    'pdf-generated-success': 'PDF gerado com sucesso!',
    'purchase-order-generated': 'Ordem de compra gerada com sucesso!',
    'requisition-document-downloaded': 'Documento da requisição baixado com sucesso!',
    'monthly-analysis-generated': 'Análise mensal gerada com sucesso!',
    'complete-report-exported': 'Relatório completo exportado com sucesso!',
    'operation-error': 'Erro na operação',
    'form-validation-error': 'Corrija os erros no formulário',
    'rejection-reason-required': 'Por favor, informe o motivo da rejeição',
    'no-data-to-export': 'Não há dados para exportar',
    'no-data-for-analysis': 'Não há dados para análise',
    'no-requisitions-for-period': 'Não há requisições para o período selecionado',
    'pdf-generation-error': 'Erro ao gerar PDF',
    'report-generation-error': 'Erro ao gerar relatório',

    // Configurações - Sistema
    'system-configurations': 'Configurações do Sistema',
    'customize-appearance-behavior': 'Personalize a aparência e comportamento do sistema',
    'theme-label': 'Tema',
    'choose-theme': 'Escolha entre tema claro ou escuro',
    'language-label': 'Idioma',
    'system-interface-language': 'Idioma da interface do sistema',
    'date-format-label': 'Formato de Data',
    'how-dates-displayed': 'Como as datas são exibidas no sistema',
    'items-per-page-label': 'Itens por Página',
    'items-displayed-tables': 'Número de itens exibidos nas tabelas',
    'about-system-title': 'Sobre o Sistema',
    'about-fuelcontrol': 'Informações sobre o Controle de Abastecimento',
    'version-label': 'Versão',
    'last-update-label': 'Última Atualização',
    'developed-by-label': 'Desenvolvido por',
    'fuelcontrol-team': 'Equipe Controle de Abastecimento',

    // Companies
    'companies': 'Empresas',
    'companies-list': 'Empresas Cadastradas',
    'new-company': 'Nova Empresa',
    'edit-company': 'Editar Empresa',
    'company-full-name': 'Nome Empresarial',
    'company-created-success': 'Empresa criada com sucesso!',
    'company-updated-success': 'Empresa atualizada com sucesso!',
    'company-deleted-success': 'Empresa excluída com sucesso!',
    'manage-client-companies': 'Gerenciar empresas clientes',

    // Gestão de Frotas
    'fleet-management': 'Gestão de Frota',
    'manage-company-vehicles': 'Gerencie os veículos da empresa',
    'search-vehicles': 'Buscar veículos...',
    'pt-filter-by-department': 'Filtrar por departamento',
    'pt-all-departments': 'Todos os departamentos',
    'new-vehicle': 'Novo Veículo',
    'edit-vehicle': 'Editar Veículo',
    'update-vehicle-info': 'Atualize as informações do veículo',
    'add-new-vehicle': 'Adicione um novo veículo à frota',
    'plate': 'Placa',
    'year': 'Ano',
    'brand': 'Marca',
    'model': 'Modelo',
    'fuel': 'Combustível',
    'mileage': 'Quilometragem',
    'last-maintenance': 'Última manutenção',
    'pt-status': 'Status',
    'active': 'Ativo',
    'pt-maintenance': 'Manutenção',
    'inactive': 'Inativo',
    'no-vehicles-found': 'Nenhum veículo encontrado',
    'adjust-filters': 'Tente ajustar seus filtros',
    'start-adding-vehicle': 'Comece adicionando um novo veículo',
    'loading-fleet': 'Carregando frota...',
    'vehicle-created-success': 'Veículo criado com sucesso',
    'vehicle-updated-success': 'Veículo atualizado com sucesso',
    'vehicle-status-changed': 'Status do veículo alterado com sucesso',
    'error-creating-vehicle': 'Erro ao criar veículo',
    'error-updating-vehicle': 'Erro ao atualizar veículo',
    'error-changing-status': 'Erro ao alterar status',

    // Gestão de Usuários
    'user-management': 'Gestão de Usuários',
    'manage-employees-permissions': 'Gerencie funcionários e suas permissões no sistema',
    'search-users': 'Buscar usuários...',
    'new-user': 'Novo Usuário',
    'edit-user': 'Editar Usuário',
    'update-user-info': 'Atualize as informações do usuário',
    'add-new-user': 'Adicione um novo usuário ao sistema',
    'pt-username': 'Nome de usuário',
    'pt-password': 'Senha',
    'pt-new-password-optional': 'Nova senha (deixe vazio para manter)',
    'pt-full-name': 'Nome completo',
    'pt-email': 'Email',
    'pt-phone': 'Telefone',
    'pt-position': 'Cargo',
    'pt-role': 'Perfil',
    'hire-date': 'Data de contratação',
    'administrator': 'Administrador',
    'manager': 'Gerente',
    'employee': 'Funcionário',
    'no-users-found': 'Nenhum usuário encontrado',
    'adjust-search': 'Tente ajustar sua busca',
    'start-creating-user': 'Comece criando um novo usuário',
    'loading-users': 'Carregando usuários...',
    'user-created-success': 'Usuário criado com sucesso',
    'user-updated-success': 'Usuário atualizado com sucesso',
    'user-status-changed': 'Status do usuário alterado com sucesso',
    'error-creating-user': 'Erro ao criar usuário',
    'error-updating-user': 'Erro ao atualizar usuário',
    'error-changing-user-status': 'Erro ao alterar status',
    'not-informed': 'Não informado',
    'no-department': 'Sem departamento',
    'department-not-found': 'Departamento não encontrado',
    'user-deleted-success': 'Usuário excluído com sucesso',
    'error-deleting-user': 'Erro ao excluir usuário',
    'confirm-delete-user': 'Tem certeza que deseja excluir este usuário?',

    // Gestão de Departamentos
    'department-management': 'Gestão de Departamentos',
    'department_management': 'Gestão de Departamentos',
    'manage-company-departments': 'Gerencie os departamentos da empresa',
    'manage_company_departments': 'Gerencie os departamentos da empresa',
    'search-departments': 'Buscar departamentos...',
    'search_departments': 'Buscar departamentos...',
    'new-department': 'Novo Departamento',
    'new_department': 'Novo Departamento',
    'edit-department': 'Editar Departamento',
    'edit_department': 'Editar Departamento',
    'update-department-info': 'Atualize as informações do departamento',
    'update_department_info': 'Atualize as informações do departamento',
    'add-new-department': 'Adicione um novo departamento',
    'add_new_department': 'Adicione um novo departamento',
    'department-name': 'Nome do departamento',
    'department_name': 'Nome do departamento',
    'description': 'Descrição',
    'pt-manager': 'Gerente',
    'budget': 'Orçamento (R$)',
    'employees': 'Funcionários',
    'no-manager': 'Sem gerente',
    'no_manager': 'Sem gerente',
    'select-manager': 'Selecione um gerente',
    'select_manager': 'Selecione um gerente',
    'manager-not-found': 'Gerente não encontrado',
    'manager_not_found': 'Gerente não encontrado',
    'no-departments-found': 'Nenhum departamento encontrado',
    'no_departments_found': 'Nenhum departamento encontrado',
    'start-creating-department': 'Comece criando um novo departamento',
    'start_creating_department': 'Comece criando um novo departamento',
    'loading-departments': 'Carregando departamentos...',
    'loading_departments': 'Carregando departamentos...',
    'department-created-success': 'Departamento criado com sucesso',
    'department_created_success': 'Departamento criado com sucesso',
    'department_created_successfully': 'Departamento criado com sucesso',
    'department-updated-success': 'Departamento atualizado com sucesso',
    'department_updated_success': 'Departamento atualizado com sucesso',
    'department_updated_successfully': 'Departamento atualizado com sucesso',
    'error-creating-department': 'Erro ao criar departamento',
    'error_creating_department': 'Erro ao criar departamento',
    'error-updating-department': 'Erro ao atualizar departamento',
    'error_updating_department': 'Erro ao atualizar departamento',
    'try-adjusting-search': 'Tente ajustar sua busca',
    'try_adjusting_search': 'Tente ajustar sua busca',
    'start-creating-new-department': 'Comece criando um novo departamento',
    'start_creating_new_department': 'Comece criando um novo departamento',
    'enter-department-name': 'Digite o nome do departamento',
    'enter_department_name': 'Digite o nome do departamento',
    'enter-department-description': 'Digite a descrição do departamento',
    'enter_department_description': 'Digite a descrição do departamento',

    // Navegação do Menu
    'users': 'Usuários',
    'departments': 'Departamentos',
    'fleet': 'Frota',

    // Dicas de segurança
    'security-tip-1': 'Use uma senha com pelo menos 6 caracteres',
    'security-tip-2': 'Inclua letras maiúsculas, minúsculas e números',
    'security-tip-3': 'Não compartilhe sua senha com outras pessoas',
    'security-tip-4': 'Altere sua senha regularmente',
    'security-tip-5': 'Evite usar informações pessoais óbvias',
  },
  'en-US': {
    // Navigation
    'dashboard': 'Dashboard',
    'requisitions': 'Requisitions',
    'new-requisition': 'New Requisition',
    'reports': 'Reports',
    'settings': 'Settings',

    // Actions
    'save': 'Save',
    'cancel': 'Cancel',
    'edit': 'Edit',
    'delete': 'Delete',
    'view': 'View',
    'print': 'Print',
    'export': 'Export',
    'import': 'Import',
    'search': 'Search',
    'filter': 'Filter',
    'clear': 'Clear',
    'submit': 'Submit',
    'close': 'Close',
    'open': 'Open',
    'add': 'Add',
    'remove': 'Remove',
    'update': 'Update',
    'create': 'Create',
    'confirm': 'Confirm',
    'approve': 'Approve',
    'reject': 'Reject',

    // States
    'loading': 'Loading...',
    'success': 'Success',
    'error': 'Error',
    'warning': 'Warning',
    'info': 'Information',
    'pending': 'Pending',
    'approved': 'Approved',
    'rejected': 'Rejected',
    'fulfilled': 'Fulfilled',
    'cancelled': 'Cancelled',

    // System
    'system-name': 'Fuel Control',
    'fuel-control-system': 'Fuel Control System',
    'profile': 'Profile',
    'security': 'Security',
    'notifications': 'Notifications',
    'system': 'System',
    'theme': 'Theme',
    'language': 'Language',
    'dark': 'Dark',
    'light': 'Light',
    'system-theme': 'System',
    'enabled': 'Enabled',
    'disabled': 'Disabled',

    // Dashboard
    'total-requests': 'Total Requests',
    'pending-requests': 'Pending Requests',
    'approved-requests': 'Approved Requests',
    'fuel-consumption': 'Fuel Consumption',
    'monthly-consumption': 'Monthly Consumption',
    'weekly-consumption': 'Weekly Consumption',
    'consumption-by-department': 'Consumption by Department',
    'consumption-by-fuel-type': 'Consumption by Fuel Type',
    'recent-activity': 'Recent Activity',
    'quick-stats': 'Quick Stats',

    // Requisitions
    'requisition': 'Requisition',
    'requisition-number': 'Requisition Number',
    'requisition-date': 'Requisition Date',
    'requester': 'Requester',
    'department': 'Department',
    'fuel-type': 'Fuel Type',
    'quantity': 'Quantity',
    'priority': 'Priority',
    'status': 'Status',
    'justification': 'Justification',
    'approver': 'Approver',
    'approval-date': 'Approval Date',
    'needed-date': 'Needed Date',
    'request-date': 'Request Date',
    'details': 'Details',
    'actions': 'Actions',

    // Fuel types
    'gasoline': 'Gasoline',
    'ethanol': 'Ethanol',
    'diesel': 'Diesel',
    'diesel-s10': 'Diesel S10',

    // Departments
    'logistics': 'Logistics',
    'maintenance': 'Maintenance',
    'administration': 'Administration',
    'operations': 'Operations',
    'transport': 'Transport',

    // Priorities
    'low': 'Low',
    'medium': 'Medium',
    'high': 'High',
    'urgent': 'Urgent',

    // Forms
    'required-field': 'Required field',
    'select-option': 'Select an option',
    'enter-value': 'Enter a value',
    'invalid-email': 'Invalid email',
    'password-too-short': 'Password too short',
    'passwords-dont-match': 'Passwords don\'t match',
    'form-errors': 'Please fix form errors',
    'form-saved': 'Form saved successfully',

    // Reports
    'generate-report': 'Generate Report',
    'report-period': 'Report Period',
    'start-date': 'Start Date',
    'end-date': 'End Date',
    'report-type': 'Report Type',
    'consumption-report': 'Consumption Report',
    'requisitions-report': 'Requisitions Report',
    'department-report': 'Department Report',
    'fuel-type-report': 'Fuel Type Report',
    'monthly-reports': 'Monthly Reports',
    'weekly-reports': 'Weekly Reports',
    'annual-reports': 'Annual Reports',

    // Settings
    'general-settings': 'General Settings',
    'user-preferences': 'User Preferences',
    'system-settings': 'System Settings',
    'notification-settings': 'Notification Settings',
    'change-password': 'Change Password',
    'current-password': 'Current Password',
    'new-password': 'New Password',
    'confirm-password': 'Confirm Password',
    'new-requisitions': 'New Requisitions',
    'pending-approvals': 'Pending Approvals',
    'requisition-status': 'Requisition Status',
    'personal-info': 'Personal Information',
    'contact-info': 'Contact Information',

    // User
    'username': 'Username',
    'full-name': 'Full name',
    'email': 'Email',
    'phone': 'Phone',
    'position': 'Position',
    'role': 'Role',
    'last-login': 'Last login',
    'account-created': 'Account created',

    // Messages
    'no-data': 'No data found',
    'no-results': 'No results found',
    'loading-data': 'Loading data...',
    'save-success': 'Saved successfully',
    'delete-success': 'Deleted successfully',
    'update-success': 'Updated successfully',
    'operation-failed': 'Operation failed',
    'confirm-delete': 'Are you sure you want to delete?',
    'confirm-action': 'Are you sure you want to continue?',
    'unsaved-changes': 'There are unsaved changes',

    // Pagination
    'page': 'Page',
    'of': 'of',
    'items-per-page': 'Items per page',
    'total-items': 'Total items',
    'previous': 'Previous',
    'next': 'Next',
    'first': 'First',
    'last': 'Last',

    // Date and time
    'today': 'Today',
    'yesterday': 'Yesterday',
    'this-week': 'This week',
    'last-week': 'Last week',
    'this-month': 'This month',
    'last-month': 'Last month',
    'this-year': 'This year',
    'date-format': 'MM/DD/YYYY',
    'time-format': 'HH:mm',

    // Print
    'print-document': 'Print Document',
    'print-preview': 'Print Preview',
    'print-options': 'Print Options',

    // About
    'version': 'Version',
    'last-update': 'Last Update',
    'developed-by': 'Developed by',
    'about-system': 'About System',
    'system-info': 'System Information',

    // Additional translations
    'filters': 'Filters',
    'search-requisitions': 'Search requisitions...',
    'filter-by-status': 'Filter by status',
    'filter-by-department': 'Filter by department',
    'all-statuses': 'All statuses',
    'all-departments': 'All departments',
    'clear-filters': 'Clear Filters',
    'no-results-with-filters': 'No requisitions found with applied filters',
    'manage-all-fuel-requisitions': 'Manage all fuel requisitions',
    'consumed-liters': 'Consumed Liters',
    'quick-actions': 'Quick Actions',
    'approve-pending': 'Approve Pending',
    'recent-requisitions': 'Recent Requisitions',
    'view-all': 'View all',
    'fuel-requisitions-overview': 'Fuel requisitions overview',
    'loading-dashboard': 'Loading dashboard...',
    'loading-reports': 'Loading reports...',
    'create-new-fuel-requisition': 'Create a new fuel requisition',
    'requisition-form': 'Requisition Form',
    'fill-required-data': 'Fill in the required data to create a new fuel requisition',
    'fuel-consumption-analysis': 'Fuel consumption analysis and statistics',
    'date': 'Date',
    'enter-full-name': 'Your full name',
    'enter-email': 'your@email.com',
    'select-department': 'Select a department',
    'enter-phone': '(11) 99999-9999',
    'enter-position': 'Your position at the company',
    'save-changes': 'Save Changes',
    'account-info': 'Account Information',
    'account-details': 'Details about your account in the system',
    'last-updated': 'Last Updated',
    'manage-profile-preferences': 'Manage your profile and system preferences',

    // Modal details
    'requisition-details': 'Requisition Details',
    'request-date-label': 'Request Date',
    'needed-date-label': 'Needed Date',
    'priority-label': 'Priority',
    'approver-label': 'Approver',
    'quantity-label': 'Quantity',
    'justification-label': 'Justification',
    'liters': 'Liters',

    // Status badges
    'pendente': 'Pending',
    'aprovada': 'Approved',
    'cumprida': 'Fulfilled',

    // Form
    'requester-label': 'Requester',
    'requester-placeholder': 'Requester name',
    'department-label': 'Department',
    'select-department-placeholder': 'Select a department',
    'fuel-type-label': 'Fuel Type',
    'select-fuel-type': 'Select fuel type',
    'quantity-liters': 'Quantity (Liters)',
    'quantity-placeholder': 'Ex: 500',
    'justification-label-form': 'Justification',
    'justification-placeholder': 'Describe the fuel necessity...',
    'needed-date-form': 'Needed Date',
    'priority-form': 'Priority',
    'medium-priority': 'Medium',
    'create-requisition': 'Create Requisition',

    // Reports
    'total-requisitions': 'Total Requisitions',
    'approval-rate': 'Approval Rate',
    'total-consumed': 'Total Consumed',
    'pending-label': 'Pending',
    'export-reports': 'Export Reports',
    'export-complete-report': 'Export Complete Report',
    'monthly-analysis': 'Monthly Analysis',
    'monthly-trend': 'Monthly Trend',
    'en-consumption-by-department': 'Consumption by Department',
    'distribution-by-fuel-type': 'Distribution by Fuel Type',
    'department-details': 'Department Details',
    'fuel-type-details': 'Fuel Type Details',
    'requisitions-count': 'Requisitions',
    'liters-count': 'Liters',
    'fuel-label': 'Fuel',

    // Settings - Security
    'change-password-title': 'Change Password',
    'keep-account-secure': 'Keep your account secure with a strong password',
    'current-password-label': 'Current Password',
    'current-password-placeholder': 'Enter your current password',
    'new-password-label': 'New Password',
    'new-password-placeholder': 'Enter your new password',
    'confirm-new-password': 'Confirm New Password',
    'confirm-password-placeholder': 'Confirm your new password',
    'change-password-button': 'Change Password',
    'security-tips': 'Security Tips',
    'keep-account-always-secure': 'Keep your account always secure',

    // Settings - Notifications
    'notification-settings-title': 'Notification Settings',
    'configure-notifications': 'Configure how and when you want to receive notifications',
    'new-requisitions-notif': 'New Requisitions',
    'new-requisitions-desc': 'Receive notifications when a new requisition is created',
    'pending-approvals-notif': 'Pending Approvals',
    'pending-approvals-desc': 'Notifications about requisitions awaiting approval',
    'requisition-status-notif': 'Requisition Status',
    'requisition-status-desc': 'Updates about the status of your requisitions',
    'monthly-reports-notif': 'Monthly Reports',
    'monthly-reports-desc': 'Monthly summary of fuel consumption',

    // Notification/toast messages
    'requisition-created-success': 'Requisition created successfully!',
    'requisition-updated-success': 'Requisition updated successfully!',
    'status-updated-success': 'Requisition status updated successfully!',
    'profile-updated-success': 'Profile updated successfully!',
    'password-changed-success': 'Password changed successfully!',
    'report-generated-success': 'Report generated successfully!',
    'pdf-generated-success': 'PDF generated successfully!',
    'purchase-order-generated': 'Purchase order generated successfully!',
    'requisition-document-downloaded': 'Requisition document downloaded successfully!',
    'monthly-analysis-generated': 'Monthly analysis generated successfully!',
    'complete-report-exported': 'Complete report exported successfully!',
    'operation-error': 'Operation error',
    'form-validation-error': 'Please fix form errors',
    'rejection-reason-required': 'Please provide rejection reason',
    'no-data-to-export': 'No data to export',
    'no-data-for-analysis': 'No data for analysis',
    'no-requisitions-for-period': 'No requisitions for selected period',
    'pdf-generation-error': 'Error generating PDF',
    'report-generation-error': 'Error generating report',
    'user-deleted-success': 'User deleted successfully',
    'error-deleting-user': 'Error deleting user',
    'confirm-delete-user': 'Are you sure you want to delete this user?',

    // Settings - System
    'system-configurations': 'System Settings',
    'customize-appearance-behavior': 'Customize system appearance and behavior',
    'theme-label': 'Theme',
    'choose-theme': 'Choose between light or dark theme',
    'language-label': 'Language',
    'system-interface-language': 'System interface language',
    'date-format-label': 'Date Format',
    'how-dates-displayed': 'How dates are displayed in the system',
    'items-per-page-label': 'Items per Page',
    'items-displayed-tables': 'Number of items displayed in tables',
    'about-system-title': 'About System',
    'about-fuelcontrol': 'Information about Fuel Control',
    'version-label': 'Version',
    'last-update-label': 'Last Update',
    'developed-by-label': 'Developed by',
    'fuelcontrol-team': 'Fuel Control Team',

    // Companies
    'companies': 'Companies',
    'companies-list': 'Company List',
    'new-company': 'New Company',
    'edit-company': 'Edit Company',
    'company-full-name': 'Company Full Name',
    'company-created-success': 'Company created successfully!',
    'company-updated-success': 'Company updated successfully!',
    'company-deleted-success': 'Company deleted successfully!',
    'manage-client-companies': 'Manage client companies',

    // Fleet Management
    'fleet-management': 'Fleet Management',
    'manage-company-vehicles': 'Manage company vehicles',
    'search-vehicles': 'Search vehicles...',
    'en-filter-by-department': 'Filter by department',
    'en-all-departments': 'All departments',
    'new-vehicle': 'New Vehicle',
    'edit-vehicle': 'Edit Vehicle',
    'update-vehicle-info': 'Update vehicle information',
    'add-new-vehicle': 'Add a new vehicle to the fleet',
    'plate': 'Plate',
    'year': 'Year',
    'brand': 'Brand',
    'model': 'Model',
    'fuel': 'Fuel',
    'mileage': 'Mileage',
    'last-maintenance': 'Last maintenance',
    'en-status': 'Status',
    'active': 'Active',
    'en-maintenance': 'Maintenance',
    'inactive': 'Inactive',
    'no-vehicles-found': 'No vehicles found',
    'adjust-filters': 'Try adjusting your filters',
    'start-adding-vehicle': 'Start by adding a new vehicle',
    'loading-fleet': 'Loading fleet...',
    'vehicle-created-success': 'Vehicle created successfully',
    'vehicle-updated-success': 'Vehicle updated successfully',
    'vehicle-status-changed': 'Vehicle status changed successfully',
    'error-creating-vehicle': 'Error creating vehicle',
    'error-updating-vehicle': 'Error updating vehicle',
    'error-changing-status': 'Error changing status',

    // User Management
    'user-management': 'User Management',
    'manage-employees-permissions': 'Manage employees and their system permissions',
    'search-users': 'Search users...',
    'new-user': 'New User',
    'edit-user': 'Edit User',
    'update-user-info': 'Update user information',
    'add-new-user': 'Add a new user to the system',
    'en-username': 'Username',
    'en-password': 'Password',
    'en-new-password-optional': 'New password (leave empty to keep)',
    'en-full-name': 'Full name',
    'en-email': 'Email',
    'en-phone': 'Phone',
    'en-position': 'Position',
    'en-role': 'Role',
    'hire-date': 'Hire date',
    'administrator': 'Administrator',
    'manager': 'Manager',
    'employee': 'Employee',
    'no-users-found': 'No users found',
    'adjust-search': 'Try adjusting your search',
    'start-creating-user': 'Start by creating a new user',
    'loading-users': 'Loading users...',
    'user-created-success': 'User created successfully',
    'user-updated-success': 'User updated successfully',
    'user-status-changed': 'User status changed successfully',
    'error-creating-user': 'Error creating user',
    'error-updating-user': 'Error updating user',
    'error-changing-user-status': 'Error changing status',
    'not-informed': 'Not informed',
    'no-department': 'No department',
    'department-not-found': 'Department not found',

    // Department Management
    'department-management': 'Department Management',
    'manage-company-departments': 'Manage company departments',
    'search-departments': 'Search departments...',
    'new-department': 'New Department',
    'edit-department': 'Edit Department',
    'update-department-info': 'Update department information',
    'add-new-department': 'Add a new department',
    'department-name': 'Department name',
    'description': 'Description',
    'department-manager': 'Manager',
    'budget': 'Budget ($)',
    'employees': 'Employees',
    'no-manager': 'No manager',
    'select-manager': 'Select a manager',
    'manager-not-found': 'Manager not found',
    'no-departments-found': 'No departments found',
    'start-creating-department': 'Start by creating a new department',
    'loading-departments': 'Loading departments...',
    'department-created-success': 'Department created successfully',
    'department-updated-success': 'Department updated successfully',
    'error-creating-department': 'Error creating department',
    'error-updating-department': 'Error updating department',
    'try-adjusting-search': 'Try adjusting your search',
    'start-creating-new-department': 'Start by creating a new department',
    'enter-department-name': 'Enter department name',
    'enter-department-description': 'Enter department description',

    // Navigation Menu
    'users': 'Users',
    'departments': 'Departments',
    'fleet': 'Fleet',

    // Suppliers
    'suppliers': 'Suppliers',
    'supplier': 'Supplier',
    'supplier-management': 'Supplier Management',
    'suppliers-list': 'Supplier List',
    'new-supplier': 'New Supplier',
    'edit-supplier': 'Edit Supplier',
    'delete-supplier': 'Delete Supplier',
    'supplier-name': 'Name',
    'supplier-cnpj': 'CNPJ',
    'supplier-responsible': 'Responsible',
    'supplier-email': 'Email',
    'supplier-phone': 'Phone',
    'supplier-address': 'Address',
    'search-suppliers': 'Search suppliers...',
    'no-suppliers': 'No suppliers found',
    'supplier-created': 'Supplier created successfully!',
    'supplier-updated': 'Supplier updated successfully!',
    'supplier-deleted': 'Supplier deleted successfully!',
    'error-creating-supplier': 'Error creating supplier',
    'error-updating-supplier': 'Error updating supplier',
    'error-deleting-supplier': 'Error deleting supplier',

    // Security tips
    'security-tip-1': 'Use a password with at least 6 characters',
    'security-tip-2': 'Include uppercase, lowercase letters and numbers',
    'security-tip-3': 'Do not share your password with others',
    'security-tip-4': 'Change your password regularly',
    'security-tip-5': 'Avoid using obvious personal information',
  },
  'es-ES': {
    // Navegación
    'dashboard': 'Tablero',
    'requisitions': 'Requisiciones',
    'new-requisition': 'Nueva Requisición',
    'reports': 'Informes',
    'settings': 'Configuraciones',

    // Acciones
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'edit': 'Editar',
    'delete': 'Eliminar',
    'view': 'Ver',
    'print': 'Imprimir',
    'export': 'Exportar',
    'import': 'Importar',
    'search': 'Buscar',
    'filter': 'Filtrar',
    'clear': 'Limpiar',
    'submit': 'Enviar',
    'close': 'Cerrar',
    'open': 'Abrir',
    'add': 'Agregar',
    'remove': 'Eliminar',
    'update': 'Actualizar',
    'create': 'Crear',
    'confirm': 'Confirmar',
    'approve': 'Aprobar',
    'reject': 'Rechazar',

    // Estados
    'loading': 'Cargando...',
    'success': 'Éxito',
    'error': 'Error',
    'warning': 'Advertencia',
    'info': 'Información',
    'pending': 'Pendiente',
    'approved': 'Aprobado',
    'rejected': 'Rechazado',
    'fulfilled': 'Realizado',
    'cancelled': 'Cancelado',

    // Sistema
    'system-name': 'Control de Combustible',
    'fuel-control-system': 'Sistema de Control de Combustible',
    'profile': 'Perfil',
    'security': 'Seguridad',
    'notifications': 'Notificaciones',
    'system': 'Sistema',
    'theme': 'Tema',
    'language': 'Idioma',
    'dark': 'Oscuro',
    'light': 'Claro',
    'system-theme': 'Sistema',
    'enabled': 'Activado',
    'disabled': 'Desactivado',

    // Tablero
    'total-requests': 'Total de Requisiciones',
    'pending-requests': 'Requisiciones Pendientes',
    'approved-requests': 'Requisiciones Aprobadas',
    'fuel-consumption': 'Consumo de Combustible',
    'monthly-consumption': 'Consumo Mensual',
    'weekly-consumption': 'Consumo Semanal',
    'consumption-by-department': 'Consumo por Departamento',
    'consumption-by-fuel-type': 'Consumo por Tipo de Combustible',
    'recent-activity': 'Actividad Reciente',
    'quick-stats': 'Estadísticas Rápidas',

    // Requisiciones
    'requisition': 'Requisición',
    'requisition-number': 'Número de Requisición',
    'requisition-date': 'Fecha de Requisición',
    'requester': 'Solicitante',
    'department': 'Departamento',
    'fuel-type': 'Tipo de Combustible',
    'quantity': 'Cantidad',
    'priority': 'Prioridad',
    'status': 'Estado',
    'justification': 'Justificación',
    'approver': 'Aprobador',
    'approval-date': 'Fecha de Aprobación',
    'needed-date': 'Fecha Necesaria',
    'request-date': 'Fecha de Solicitud',
    'details': 'Detalles',
    'actions': 'Acciones',

    // Tipos de combustible
    'gasoline': 'Gasolina',
    'ethanol': 'Etanol',
    'diesel': 'Diésel',
    'diesel-s10': 'Diésel S10',

    // Departamentos
    'logistics': 'Logística',
    'maintenance': 'Mantenimiento',
    'administration': 'Administración',
    'operations': 'Operaciones',
    'transport': 'Transporte',

    // Prioridades
    'low': 'Baja',
    'medium': 'Media',
    'high': 'Alta',
    'urgent': 'Urgente',

    // Formularios
    'required-field': 'Campo requerido',
    'select-option': 'Seleccione una opción',
    'enter-value': 'Ingrese un valor',
    'invalid-email': 'Email inválido',
    'password-too-short': 'Contraseña muy corta',
    'passwords-dont-match': 'Las contraseñas no coinciden',
    'form-errors': 'Corrija los errores del formulario',
    'form-saved': 'Formulario guardado exitosamente',

    // Informes
    'generate-report': 'Generar Informe',
    'report-period': 'Período del Informe',
    'start-date': 'Fecha de Inicio',
    'end-date': 'Fecha de Fin',
    'report-type': 'Tipo de Informe',
    'consumption-report': 'Informe de Consumo',
    'requisitions-report': 'Informe de Requisiciones',
    'department-report': 'Informe por Departamento',
    'fuel-type-report': 'Informe por Tipo de Combustible',
    'monthly-reports': 'Informes Mensuales',
    'weekly-reports': 'Informes Semanales',
    'annual-reports': 'Informes Anuales',

    // Configuraciones
    'general-settings': 'Configuraciones Generales',
    'user-preferences': 'Preferencias del Usuario',
    'system-settings': 'Configuraciones del Sistema',
    'notification-settings': 'Configuraciones de Notificación',
    'change-password': 'Cambiar Contraseña',
    'current-password': 'Contraseña Actual',
    'new-password': 'Nueva Contraseña',
    'confirm-password': 'Confirmar Contraseña',
    'new-requisitions': 'Nuevas Requisiciones',
    'pending-approvals': 'Aprobaciones Pendientes',
    'requisition-status': 'Estado de Requisiciones',
    'personal-info': 'Información Personal',
    'contact-info': 'Información de Contacto',

    // Usuario
    'username': 'Nombre de usuario',
    'full-name': 'Nombre completo',
    'email': 'Correo electrónico',
    'phone': 'Teléfono',
    'position': 'Cargo',
    'role': 'Rol',
    'last-login': 'Último acceso',
    'account-created': 'Cuenta creada',

    // Mensajes
    'no-data': 'No se encontraron datos',
    'no-results': 'No se encontraron resultados',
    'loading-data': 'Cargando datos...',
    'save-success': 'Guardado exitosamente',
    'delete-success': 'Eliminado exitosamente',
    'update-success': 'Actualizado exitosamente',
    'operation-failed': 'Operación falló',
    'confirm-delete': '¿Está seguro que desea eliminar?',
    'confirm-action': '¿Está seguro que desea continuar?',
    'unsaved-changes': 'Hay cambios sin guardar',

    // Paginación
    'page': 'Página',
    'of': 'de',
    'items-per-page': 'Elementos por página',
    'total-items': 'Total de elementos',
    'previous': 'Anterior',
    'next': 'Siguiente',
    'first': 'Primero',
    'last': 'Último',

    // Fecha y hora
    'today': 'Hoy',
    'yesterday': 'Ayer',
    'this-week': 'Esta semana',
    'last-week': 'Semana pasada',
    'this-month': 'Este mes',
    'last-month': 'Mes pasado',
    'this-year': 'Este año',
    'date-format': 'DD/MM/AAAA',
    'time-format': 'HH:mm',

    // Impresión
    'print-document': 'Imprimir Documento',
    'print-preview': 'Vista Previa de Impresión',
    'print-options': 'Opciones de Impresión',

    // Acerca de
    'version': 'Versión',
    'last-update': 'Última Actualización',
    'developed-by': 'Desarrollado por',
    'about-system': 'Acerca del Sistema',
    'system-info': 'Información del Sistema',

    // Traducciones adicionales
    'filters': 'Filtros',
    'search-requisitions': 'Buscar requisiciones...',
    'filter-by-status': 'Filtrar por estado',
    'filter-by-department': 'Filtrar por departamento',
    'all-statuses': 'Todos los estados',
    'all-departments': 'Todos los departamentos',
    'clear-filters': 'Limpiar Filtros',
    'no-results-with-filters': 'No se encontraron requisiciones con los filtros aplicados',
    'manage-all-fuel-requisitions': 'Gestionar todas las requisiciones de combustible',
    'consumed-liters': 'Litros Consumidos',
    'quick-actions': 'Acciones Rápidas',
    'approve-pending': 'Aprobar Pendientes',
    'recent-requisitions': 'Requisiciones Recientes',
    'view-all': 'Ver todas',
    'fuel-requisitions-overview': 'Resumen de requisiciones de combustible',
    'loading-dashboard': 'Cargando tablero...',
    'loading-reports': 'Cargando informes...',
    'create-new-fuel-requisition': 'Crear una nueva requisición de combustible',
    'requisition-form': 'Formulario de Requisición',
    'fill-required-data': 'Complete los datos necesarios para crear una nueva requisición de combustible',
    'fuel-consumption-analysis': 'Análisis y estadísticas de consumo de combustible',
    'date': 'Fecha',
    'enter-full-name': 'Su nombre completo',
    'enter-email': 'su@email.com',
    'select-department': 'Seleccione un departamento',
    'enter-phone': '(11) 99999-9999',
    'enter-position': 'Su cargo en la empresa',
    'save-changes': 'Guardar Cambios',
    'account-info': 'Información de la Cuenta',
    'account-details': 'Detalles sobre su cuenta en el sistema',
    'last-updated': 'Última Actualización',
    'manage-profile-preferences': 'Gestione su perfil y preferencias del sistema',

    // Detalles del modal
    'requisition-details': 'Detalles de la Requisición',
    'request-date-label': 'Fecha de Solicitud',
    'needed-date-label': 'Fecha Necesaria',
    'priority-label': 'Prioridad',
    'approver-label': 'Aprobador',
    'quantity-label': 'Cantidad',
    'justification-label': 'Justificación',
    'liters': 'Litros',

    // Badges de estado
    'pendente': 'Pendiente',
    'aprovada': 'Aprobada',
    'cumprida': 'Cumplida',

    // Formulario
    'requester-label': 'Solicitante',
    'requester-placeholder': 'Nombre del solicitante',
    'department-label': 'Departamento',
    'select-department-placeholder': 'Seleccione un departamento',
    'fuel-type-label': 'Tipo de Combustible',
    'select-fuel-type': 'Seleccione el combustible',
    'quantity-liters': 'Cantidad (Litros)',
    'quantity-placeholder': 'Ej: 500',
    'justification-label-form': 'Justificación',
    'justification-placeholder': 'Describa la necesidad del combustible...',
    'needed-date-form': 'Fecha Necesaria',
    'priority-form': 'Prioridad',
    'medium-priority': 'Media',
    'create-requisition': 'Crear Requisición',

    // Informes
    'total-requisitions': 'Total de Requisiciones',
    'approval-rate': 'Tasa de Aprobación',
    'total-consumed': 'Total Consumido',
    'pending-label': 'Pendientes',
    'export-reports': 'Exportar Informes',
    'export-complete-report': 'Exportar Informe Completo',
    'monthly-analysis': 'Análisis Mensual',
    'monthly-trend': 'Tendencia Mensual',
    'es-consumption-by-department': 'Consumo por Departamento',
    'distribution-by-fuel-type': 'Distribución por Tipo de Combustible',
    'department-details': 'Detalles por Departamento',
    'fuel-type-details': 'Detalles por Tipo de Combustible',
    'requisitions-count': 'Requisiciones',
    'liters-count': 'Litros',
    'fuel-label': 'Combustible',

    // Configuraciones - Seguridad
    'change-password-title': 'Cambiar Contraseña',
    'keep-account-secure': 'Mantenga su cuenta segura con una contraseña fuerte',
    'current-password-label': 'Contraseña Actual',
    'current-password-placeholder': 'Ingrese su contraseña actual',
    'new-password-label': 'Nueva Contraseña',
    'new-password-placeholder': 'Ingrese su nueva contraseña',
    'confirm-new-password': 'Confirmar Nueva Contraseña',
    'confirm-password-placeholder': 'Confirme su nueva contraseña',
    'change-password-button': 'Cambiar Contraseña',
    'security-tips': 'Consejos de Seguridad',
    'keep-account-always-secure': 'Mantenga su cuenta siempre segura',

    // Configuraciones - Notificaciones
    'notification-settings-title': 'Configuraciones de Notificación',
    'configure-notifications': 'Configure cómo y cuándo desea recibir notificaciones',
    'new-requisitions-notif': 'Nuevas Requisiciones',
    'new-requisitions-desc': 'Reciba notificaciones cuando se cree una nueva requisición',
    'pending-approvals-notif': 'Aprobaciones Pendientes',
    'pending-approvals-desc': 'Notificaciones sobre requisiciones esperando aprobación',
    'requisition-status-notif': 'Estado de Requisiciones',
    'requisition-status-desc': 'Actualizaciones sobre el estado de sus requisiciones',
    'monthly-reports-notif': 'Informes Mensuales',
    'monthly-reports-desc': 'Resumen mensual del consumo de combustible',

    // Mensajes de notificación/toast
    'requisition-created-success': '¡Requisición creada con éxito!',
    'requisition-updated-success': '¡Requisición actualizada con éxito!',
    'status-updated-success': '¡Estado de requisición actualizado con éxito!',
    'profile-updated-success': '¡Perfil actualizado con éxito!',
    'password-changed-success': '¡Contraseña cambiada con éxito!',
    'report-generated-success': '¡Informe generado con éxito!',
    'pdf-generated-success': '¡PDF generado con éxito!',
    'purchase-order-generated': '¡Orden de compra generada con éxito!',
    'requisition-document-downloaded': '¡Documento de requisición descargado con éxito!',
    'monthly-analysis-generated': '¡Análisis mensual generado con éxito!',
    'complete-report-exported': '¡Informe completo exportado con éxito!',
    'operation-error': 'Error en la operación',
    'form-validation-error': 'Por favor corrija los errores del formulario',
    'rejection-reason-required': 'Por favor proporcione el motivo del rechazo',
    'no-data-to-export': 'No hay datos para exportar',
    'no-data-for-analysis': 'No hay datos para análisis',
    'no-requisitions-for-period': 'No hay requisiciones para el período seleccionado',
    'pdf-generation-error': 'Error al generar PDF',
    'report-generation-error': 'Error al generar informe',
    'user-deleted-success': 'Usuario eliminado con éxito',
    'error-deleting-user': 'Error al eliminar usuario',
    'confirm-delete-user': '¿Está seguro que desea eliminar este usuario?',

    // Configuraciones - Sistema
    'system-configurations': 'Configuraciones del Sistema',
    'customize-appearance-behavior': 'Personalice la apariencia y comportamiento del sistema',
    'theme-label': 'Tema',
    'choose-theme': 'Elija entre tema claro u oscuro',
    'language-label': 'Idioma',
    'system-interface-language': 'Idioma de la interfaz del sistema',
    'date-format-label': 'Formato de Fecha',
    'how-dates-displayed': 'Cómo se muestran las fechas en el sistema',
    'items-per-page-label': 'Elementos por Página',
    'items-displayed-tables': 'Número de elementos mostrados en las tablas',
    'about-system-title': 'Acerca del Sistema',
    'about-fuelcontrol': 'Información sobre Control de Combustible',
    'version-label': 'Versión',
    'last-update-label': 'Última Actualización',
    'developed-by-label': 'Desarrollado por',
    'fuelcontrol-team': 'Equipo Control de Combustible',

    // Empresas
    'companies': 'Empresas',
    'companies-list': 'Lista de Empresas',
    'new-company': 'Nueva Empresa',
    'edit-company': 'Editar Empresa',
    'company-full-name': 'Nombre Empresarial',
    'company-created-success': '¡Empresa creada exitosamente!',
    'company-updated-success': '¡Empresa actualizada exitosamente!',
    'company-deleted-success': '¡Empresa eliminada exitosamente!',
    'manage-client-companies': 'Gestionar empresas clientes',

    // Gestión de Flota
    'fleet-management': 'Gestión de Flota',
    'manage-company-vehicles': 'Gestione los vehículos de la empresa',
    'search-vehicles': 'Buscar vehículos...',
    'es-filter-by-department': 'Filtrar por departamento',
    'es-all-departments': 'Todos los departamentos',
    'new-vehicle': 'Nuevo Vehículo',
    'edit-vehicle': 'Editar Vehículo',
    'update-vehicle-info': 'Actualice la información del vehículo',
    'add-new-vehicle': 'Agregue un nuevo vehículo a la flota',
    'plate': 'Placa',
    'year': 'Año',
    'brand': 'Marca',
    'model': 'Modelo',
    'fuel': 'Combustibile',
    'mileage': 'Kilometraje',
    'last-maintenance': 'Último mantenimiento',
    'es-status': 'Estado',
    'active': 'Activo',
    'es-maintenance': 'Mantenimiento',
    'inactive': 'Inactivo',
    'no-vehicles-found': 'No se encontraron vehículos',
    'adjust-filters': 'Intente ajustar sus filtros',
    'start-adding-vehicle': 'Comience agregando un nuevo vehículo',
    'loading-fleet': 'Cargando flota...',
    'vehicle-created-success': 'Vehículo creado exitosamente',
    'vehicle-updated-success': 'Vehículo actualizado exitosamente',
    'vehicle-status-changed': 'Estado del vehículo cambiado exitosamente',
    'error-creating-vehicle': 'Error al crear vehículo',
    'error-updating-vehicle': 'Error al actualizar vehículo',
    'error-changing-status': 'Error al cambiar estado',

    // Gestión de Usuarios
    'user-management': 'Gestión de Usuarios',
    'manage-employees-permissions': 'Gestione empleados y sus permisos del sistema',
    'search-users': 'Buscar usuarios...',
    'new-user': 'Nuevo Usuario',
    'edit-user': 'Editar Usuario',
    'update-user-info': 'Actualice la información del usuario',
    'add-new-user': 'Agregue un nuevo usuario al sistema',
    'es-username': 'Nombre de usuario',
    'es-password': 'Contraseña',
    'es-new-password-optional': 'Nueva contraseña (deje vacío para mantener)',
    'es-full-name': 'Nombre completo',
    'es-email': 'Correo electrónico',
    'es-phone': 'Teléfono',
    'es-position': 'Cargo',
    'es-role': 'Rol',
    'hire-date': 'Fecha de contratación',
    'administrator': 'Administrador',
    'manager': 'Gerente',
    'employee': 'Empleado',
    'no-users-found': 'No se encontraron usuarios',
    'adjust-search': 'Intente ajustar su búsqueda',
    'start-creating-user': 'Comience creando un nuevo usuario',
    'loading-users': 'Cargando usuarios...',
    'user-created-success': 'Usuario creado exitosamente',
    'user-updated-success': 'Usuario actualizado exitosamente',
    'user-status-changed': 'Estado del usuario cambiado exitosamente',
    'error-creating-user': 'Error al crear usuario',
    'error-updating-user': 'Error al actualizar usuario',
    'error-changing-user-status': 'Error al cambiar estado',
    'not-informed': 'No informado',
    'no-department': 'Sin departamento',
    'department-not-found': 'Departamento no encontrado',

    // Gestión de Departamentos
    'department-management': 'Gestión de Departamentos',
    'manage-company-departments': 'Gestione los departamentos de la empresa',
    'search-departments': 'Buscar departamentos...',
    'new-department': 'Nuevo Departamento',
    'edit-department': 'Editar Departamento',
    'update-department-info': 'Actualice la información del departamento',
    'add-new-department': 'Agregue un nuevo departamento',
    'department-name': 'Nombre del departamento',
    'description': 'Descripción',
    'department-manager': 'Gerente del departamento',
    'budget': 'Presupuesto ($)',
    'employees': 'Empleados',
    'no-manager': 'Sin gerente',
    'select-manager': 'Seleccione un gerente',
    'manager-not-found': 'Gerente no encontrado',
    'no-departments-found': 'No se encontraron departamentos',
    'start-creating-department': 'Comience creando un nuevo departamento',
    'loading-departments': 'Cargando departamentos...',
    'department-created-success': 'Departamento creado exitosamente',
    'department-updated-success': 'Departamento actualizado exitosamente',
    'error-creating-department': 'Error al crear departamento',
    'error-updating-department': 'Error al actualizar departamento',
    'try-adjusting-search': 'Intente ajustar su búsqueda',
    'start-creating-new-department': 'Comience creando un nuevo departamento',
    'enter-department-name': 'Ingrese el nombre del departamento',
    'enter-department-description': 'Ingrese la descripción del departamento',

    // Navegación del Menú
    'users': 'Usuarios',
    'departments': 'Departamentos',
    'fleet': 'Flota',

    // Proveedores
    'suppliers': 'Proveedores',
    'supplier': 'Proveedor',
    'supplier-management': 'Gestión de Proveedores',
    'suppliers-list': 'Lista de Proveedores',
    'new-supplier': 'Nuevo Proveedor',
    'edit-supplier': 'Editar Proveedor',
    'delete-supplier': 'Eliminar Proveedor',
    'supplier-name': 'Nombre',
    'supplier-cnpj': 'CNPJ',
    'supplier-responsible': 'Responsable',
    'supplier-email': 'Email',
    'supplier-phone': 'Teléfono',
    'supplier-address': 'Dirección',
    'search-suppliers': 'Buscar proveedores...',
    'no-suppliers': 'No se encontraron proveedores',
    'supplier-created': '¡Proveedor creado exitosamente!',
    'supplier-updated': '¡Proveedor actualizado exitosamente!',
    'supplier-deleted': '¡Proveedor eliminado exitosamente!',
    'error-creating-supplier': 'Error al crear proveedor',
    'error-updating-supplier': 'Error al actualizar proveedor',
    'error-deleting-supplier': 'Error al eliminar proveedor',

    // Consejos de seguridad
    'security-tip-1': 'Use una contraseña con al menos 6 caracteres',
    'security-tip-2': 'Incluya letras mayúsculas, minúsculas y números',
    'security-tip-3': 'No comparta su contraseña con otras personas',
    'security-tip-4': 'Cambie su contraseña regularmente',
    'security-tip-5': 'Evite usar información personal obvia',
  },
};

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'pt-BR';
  });

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
    localStorage.setItem('language', newLanguage);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}